create sequence revinfo_seq start with 1 increment by 50;

create table revinfo (
    rev integer primary key,
    revtstmp bigint
);

create table mesas (
    id bigint generated by default as identity primary key,
    numero integer not null unique check (numero > 0),
    status varchar(20) not null check (status in ('LIVRE', 'OCUPADA'))
);

create table produtos (
    id bigint generated by default as identity primary key,
    nome varchar(255) not null,
    descricao varchar(255) not null,
    categoria varchar(20) not null check (categoria in ('PORCAO', 'SALGADO', 'BEBIDA', 'PRATO_FEITO', 'SOBREMESA')),
    preco numeric(10, 2) not null check (preco > 0),
    disponivel boolean not null
);

create table comandas (
    id bigint generated by default as identity primary key,
    mesa_id bigint not null references mesas(id),
    status varchar(20) not null check (status in ('ABERTA', 'FECHADA', 'CANCELADA')),
    aberta_em timestamp not null,
    fechada_em timestamp
);

create table itens_comanda (
    id bigint generated by default as identity primary key,
    comanda_id bigint not null references comandas(id),
    produto_id bigint not null references produtos(id),
    quantidade integer not null check (quantidade > 0),
    preco_unitario numeric(10, 2) not null check (preco_unitario > 0)
);

create unique index ux_comandas_mesa_aberta on comandas (mesa_id) where status = 'ABERTA';
create index ix_comandas_status_aberta_em on comandas (status, aberta_em desc);
create index ix_itens_comanda_comanda on itens_comanda (comanda_id);
create index ix_itens_comanda_produto on itens_comanda (produto_id);
create index ix_produtos_categoria_disponivel on produtos (categoria, disponivel);

create table mesas_aud (
    rev integer not null references revinfo(rev),
    revtype smallint,
    id bigint not null,
    numero integer,
    status varchar(20),
    primary key (rev, id)
);

create table produtos_aud (
    rev integer not null references revinfo(rev),
    revtype smallint,
    id bigint not null,
    nome varchar(255),
    descricao varchar(255),
    categoria varchar(20),
    preco numeric(10, 2),
    disponivel boolean,
    primary key (rev, id)
);

create table comandas_aud (
    rev integer not null references revinfo(rev),
    revtype smallint,
    id bigint not null,
    mesa_id bigint,
    status varchar(20),
    aberta_em timestamp,
    fechada_em timestamp,
    primary key (rev, id)
);

create table itens_comanda_aud (
    rev integer not null references revinfo(rev),
    revtype smallint,
    id bigint not null,
    comanda_id bigint,
    produto_id bigint,
    quantidade integer,
    preco_unitario numeric(10, 2),
    primary key (rev, id)
);
