spring:
  application:
    name: Pb_BarPeSujo
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:pesujo}
    username: ${POSTGRES_USER:pesujo}
    password: ${POSTGRES_PASSWORD}
  flyway:
    enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 50
        envers:
          store_data_at_delete: true

  data:
    web:
      pageable:
        max-page-size: 100

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

server:
  port: 8080
